package InterfaceRelogio2;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingWorker;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luiz Fillipe
 */
public class View extends javax.swing.JFrame {
    Thread thorario;
    Relogio hora;
    Horario horario1;
    
    
    /**
     * Creates new form View
     */
    public View() {
        initComponents();    
        
        horario1 = new Horario();
        thorario = new Thread(horario1);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonAtualiza = new javax.swing.JButton();
        campoHora = new javax.swing.JTextField();
        campoMinuto = new javax.swing.JTextField();
        campoSegundo = new javax.swing.JTextField();
        DisplayRelogio = new javax.swing.JLabel();
        campoHoraDesp = new javax.swing.JTextField();
        campoMinutoDesp = new javax.swing.JTextField();
        campoSegundoDesp = new javax.swing.JTextField();
        buttonDespertar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        label1.setText("label1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-830, -150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Relógio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 190, 90));

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        buttonAtualiza.setText("Atualizar");
        buttonAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAtualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        campoHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoHoraActionPerformed(evt);
            }
        });
        jPanel1.add(campoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, -1));
        jPanel1.add(campoMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, -1));

        campoSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSegundoActionPerformed(evt);
            }
        });
        jPanel1.add(campoSegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 60, -1));

        DisplayRelogio.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jPanel1.add(DisplayRelogio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 340, 80));
        jPanel1.add(campoHoraDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, -1));

        campoMinutoDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMinutoDespActionPerformed(evt);
            }
        });
        jPanel1.add(campoMinutoDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 60, -1));
        jPanel1.add(campoSegundoDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, -1));

        buttonDespertar.setText("Despertar");
        buttonDespertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDespertarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDespertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luiz Fillipe\\Documents\\NetBeansProjects\\RelogioInterface\\1155011.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //hora.setHorario(12, 12, 12);
        thorario.start();
    }//GEN-LAST:event_formWindowOpened

    private void campoSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSegundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSegundoActionPerformed

    private void buttonAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizaActionPerformed
        int hora, minuto, segundo;
        hora = Integer.parseInt(campoHora.getText()) ;
        minuto = Integer.parseInt(campoMinuto.getText()) ;
        segundo = Integer.parseInt(campoSegundo.getText()) ;
        Relogio.hora = hora;
        Relogio.minuto = minuto;
        Relogio.segundo = segundo;
    }//GEN-LAST:event_buttonAtualizaActionPerformed

    private void campoHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoHoraActionPerformed

    private void campoMinutoDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMinutoDespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMinutoDespActionPerformed

    private void buttonDespertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDespertarActionPerformed
        // TODO add your handling code here:
        int hora, minuto, segundo;
        hora = Integer.parseInt(campoHoraDesp.getText()) ;
        minuto = Integer.parseInt(campoMinutoDesp.getText()) ;
        segundo = Integer.parseInt(campoSegundoDesp.getText()) ;
        Relogio.hora_desp = hora;
        Relogio.min_desp = minuto;
        Relogio.seg_desp = segundo;

    }//GEN-LAST:event_buttonDespertarActionPerformed

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel DisplayRelogio;
    private static javax.swing.JButton buttonAtualiza;
    private javax.swing.JButton buttonDespertar;
    public static javax.swing.JTextField campoHora;
    private javax.swing.JTextField campoHoraDesp;
    private javax.swing.JTextField campoMinuto;
    private javax.swing.JTextField campoMinutoDesp;
    public static javax.swing.JTextField campoSegundo;
    private javax.swing.JTextField campoSegundoDesp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables


}


