/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inter;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author Luiz Fillipe
 */
public class Transferencia extends javax.swing.JFrame {
private Corrente ContaAtual = new Corrente(); //Objeto serve para toda essa interface grafica
private Corrente ContaAtual2 = new Corrente(); //Objeto serve para toda essa interface grafica

    /**
     * Creates new form Transferencia
     */
    public Transferencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AgenciaOrigem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ContaOrigem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Buscar1 = new javax.swing.JButton();
        ContaDestino = new javax.swing.JTextField();
        AgenciaDestino = new javax.swing.JTextField();
        LabelAgenciaDestino = new javax.swing.JLabel();
        LabelContaDestino = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Buscar2 = new javax.swing.JButton();
        ValorTransferencia = new javax.swing.JTextField();
        Transferir = new javax.swing.JButton();
        LabelTransferencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transferência entre Contas Correntes");

        jLabel2.setText("Agência:");

        AgenciaOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaOrigemActionPerformed(evt);
            }
        });

        jLabel3.setText("Número da Conta:");

        ContaOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaOrigemActionPerformed(evt);
            }
        });

        jLabel4.setText("Origem:");

        Buscar1.setText("Buscar");
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });

        ContaDestino.setEnabled(false);
        ContaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaDestinoActionPerformed(evt);
            }
        });

        AgenciaDestino.setEnabled(false);
        AgenciaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaDestinoActionPerformed(evt);
            }
        });

        LabelAgenciaDestino.setText("Agência:");
        LabelAgenciaDestino.setEnabled(false);

        LabelContaDestino.setText("Número da Conta:");
        LabelContaDestino.setEnabled(false);

        jLabel6.setText("Destino:");

        Buscar2.setText("Buscar");
        Buscar2.setEnabled(false);
        Buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AgenciaDestino)
                            .addComponent(LabelAgenciaDestino))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(ContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Buscar2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LabelContaDestino)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AgenciaOrigem)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(ContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Buscar1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgenciaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAgenciaDestino)
                    .addComponent(LabelContaDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgenciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar2))
                .addContainerGap())
        );

        ValorTransferencia.setEnabled(false);
        ValorTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorTransferenciaActionPerformed(evt);
            }
        });

        Transferir.setText("Transferir");
        Transferir.setEnabled(false);
        Transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferirActionPerformed(evt);
            }
        });

        LabelTransferencia.setText("Valor da Transferência");
        LabelTransferencia.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTransferencia)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Transferir)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTransferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Transferir))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgenciaOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgenciaOrigemActionPerformed

    private void ContaOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContaOrigemActionPerformed

    private void ValorTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTransferenciaActionPerformed

    private void TransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferirActionPerformed
        // TODO add your handling code here:
        if(ValorTransferencia.getText() != ""){
            if (ContaAtual2.getSaldo() + ContaAtual2.getLimite() >= Double.parseDouble(ValorTransferencia.getText())){
                java.util.Date dataAtual = new Date();
                String dataFormatada = java.text.DateFormat.getDateInstance(DateFormat.MEDIUM).format(dataAtual);
                ContaAtual2.Sacar(2, "TED Enviado", dataFormatada, Double.parseDouble(ValorTransferencia.getText()));
                JOptionPane.showMessageDialog(null,"Transferencia Realizada com Sucesso!","Informação",INFORMATION_MESSAGE);
                ContaAtual2.imprimirDados();
                setVisible(false);
                dispose();
                //ContaAtual.Depositar(1, "TED Recebido", dataFormatada, Double.parseDouble(ValorTransferencia.getText()));
            }
            else
            JOptionPane.showMessageDialog(null,"Saldo insuficiente!","Informação",INFORMATION_MESSAGE);

        }
        else
        JOptionPane.showMessageDialog(null,"Informe o valor de deposito","Informação",INFORMATION_MESSAGE);
    }//GEN-LAST:event_TransferirActionPerformed

    private void AgenciaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgenciaDestinoActionPerformed

    private void ContaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContaDestinoActionPerformed

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
        // TODO add your handling code here:
        boolean encontrou = false;  //Flag para garantir se encontrou ou não a conta buscada
        int tamanho = Inter.ListaContaCorrente.size();
        for (int k = 0; k < tamanho; k++){
            ContaAtual2 = Inter.ListaContaCorrente.get(k);
            if (ContaAtual2.getAgencia() == Integer.parseInt(AgenciaOrigem.getText()) &&
                ContaAtual2.getConta() == Integer.parseInt(ContaOrigem.getText())) {
                LabelAgenciaDestino.setEnabled(true);
                LabelContaDestino.setEnabled(true);
                AgenciaDestino.setEnabled(true);
                ContaDestino.setEnabled(true);
                Buscar2.setEnabled(true);
                
                encontrou = true;
                break; //isso de nodo a parar no objeto atual
            }
        }
        if(!encontrou){
            JOptionPane.showMessageDialog(null,"Conta não encontrada","Informação",INFORMATION_MESSAGE);   JOptionPane.showMessageDialog(null,"Conta não encontrada","Informação",INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_Buscar1ActionPerformed

    private void Buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar2ActionPerformed
        // TODO add your handling code here:
        boolean encontrou = false;  //Flag para garantir se encontrou ou não a conta buscada
        int tamanho = Inter.ListaContaCorrente.size();
        for (int k = 0; k < tamanho; k++){
            ContaAtual = Inter.ListaContaCorrente.get(k);
            if (ContaAtual.getAgencia() == Integer.parseInt(AgenciaDestino.getText()) &&
                ContaAtual.getConta() == Integer.parseInt(ContaDestino.getText())) {
                LabelTransferencia.setEnabled(true);
                ValorTransferencia.setEnabled(true);
                Transferir.setEnabled(true);
                encontrou = true;
                break; //isso de nodo a parar no objeto atual
            }
        }
        if(!encontrou){
            JOptionPane.showMessageDialog(null,"Conta não encontrada","Informação",INFORMATION_MESSAGE);   JOptionPane.showMessageDialog(null,"Conta não encontrada","Informação",INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Buscar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgenciaDestino;
    private javax.swing.JTextField AgenciaOrigem;
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton Buscar2;
    private javax.swing.JTextField ContaDestino;
    private javax.swing.JTextField ContaOrigem;
    private javax.swing.JLabel LabelAgenciaDestino;
    private javax.swing.JLabel LabelContaDestino;
    private javax.swing.JLabel LabelTransferencia;
    private javax.swing.JButton Transferir;
    private javax.swing.JTextField ValorTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
